### ISSUE TITLE
Irmin tests are failing with some stores

### ISSUE THREAD

**Issue by pascutto** [g2p/mirage-storage#51]
Namely `Wodan_irmin.Make` and `Wodan_irmin.KV` are failing 5 tests.
I still still don't know why but I'll try to find out. Did you already investigate this @g2p ?

**Comment by pascutto** [comment]
Also, we should probably include all provided interfaces in the tests.

**Comment by g2p** [comment]
I think Make and non-chunked KV just fail because there are tests with big values, and chunking is required to break down these large values?

**Comment by g2p** [comment]
I just checked: tests 0, 13, and 15 failures at least are related to tombstones.

The Irmin backend needs tombstone support since we provide the RW interface which features a delete operation, but since tombstones are currently empty values (see #7), some of the Irmin interfaces we provide become ambiguous.
CA_BUILDER makes sure that values are unambiguous, but AO_BUILDER and RW_BUILDER fail to check.
Chunking adds some metadata and prevents empty values from appearing, by happy accident.

This could be solved with #7 (adding at least one byte of metadata to all Wodan values), or it could be solved by tweaking the serialisation of Irmin.Type at the wodan-irmin level.
