### ISSUE TITLE
Dunify mirage-solo5

### ISSUE THREAD

**Issue by g2p** [g2p/mirage-storage#64]
This will allow progress on #14.
@mato, is there anything we should be aware of before doing this?

**Comment by mato** [comment]
@g2p Is this dunification specific to wodan use of mirage-solo5, or for https://github.com/mirage/mirage-solo5 in general? If for general use, perhaps we should discuss it in an issue there rather than on the wodan repo?

Note that if for general use, I'd appreciate dunifying _all_ the Mirage/Solo5 packages in one go (mirage-{block,bootvar,console,net}-solo5, and mirage-solo5 itself) so that we don't have to deal with separate build systems and workflows in the long run. (/cc @pascutto @hannesm)

'll follow up with more on what you need to watch out for once we settle on where to discuss it.

**Comment by g2p** [comment]
Issue created: https://github.com/mirage/mirage-solo5/issues/41

**Comment by mato** [comment]
Ok, I've commented there
